FROM node:latest

WORKDIR /app

COPY ./public /app/public
COPY ./src /app/src
COPY ./package*.json /app/

RUN npm install
# Set the environment variable for Node.js to use legacy crypto policy
ENV NODE_OPTIONS=--openssl-legacy-provider

CMD ["npm", "start"]
