version: '3.8'

services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    networks:
      - default  # nginx-networkをdefaultに変更しました

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - default  # nginx-networkをdefaultに変更しました

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - web
      - api
    networks:
      - default  # nginx-networkをdefaultに変更しました

networks:
  default:
    external:
      name: nginx-network

# docker network create nginx-network
# npm install & npm run build(<- rm -rf node_modules rm package-lock.json npm install )
